/* auto-generated by napi-derive — do not edit by hand.
 * Regenerate after changing Rust #[napi] exports or their /// doc comments:
 *   pnpm run gen-dts:napi
 */

/**
 * Resolve `path` to its git repository's worktree root.
 *
 * Walks parent directories upward (via gitoxide's discovery logic) until a
 * `.git` directory is found. Returns the canonical worktree root as a string,
 * or `null` if `path` is not inside a git repository.
 *
 * This is a **read-path** helper — gitoxide is used, no `git` subprocess is
 * spawned.
 */
export declare function discoverRepo(path: string): string | null

/**
 * Request a batch of commit graph rows from the Rust core.
 *
 * # Arguments
 *
 * * `repo_path` — absolute path to the git worktree or `.git` directory.
 * * `offset`    — number of commits already loaded (for incremental paging).
 * * `limit`     — maximum number of commits to return in this batch.
 *
 * # Returns
 *
 * A `Buffer` containing the binary-encoded batch (see `crates/core/src/serialize.rs`).
 * The webview reads this with `DataView` / typed-array views without JSON parsing.
 *
 * # Paging (M1 implementation)
 *
 * M1 re-walks `offset + limit` commits on every call and slices the layout result.
 * This is correct but not optimal for large repos.
 *
 * TODO(M2): accept a serialised `BoundaryState` token so the host can resume layout
 * from the previous batch boundary instead of recomputing from the repository root.
 */
export declare function getGraphBatch(repoPath: string, offset: number, limit: number): Buffer

/**
 * A single file-level change introduced by a commit (vs its first parent).
 *
 * `status` is `"A"` (added), `"M"` (modified), or `"D"` (deleted).
 * `old_oid` / `new_oid` are full 40-char hex blob OIDs; the missing side of an
 * add/delete is an empty string `""`.  Rename detection is disabled; renames
 * appear as a deletion + an addition.
 *
 * napi-rs maps snake_case → camelCase in TypeScript.
 */
export interface FileChange {
  path: string
  status: string
  oldOid: string
  newOid: string
}

/**
 * Full detail of a single commit, for the commit detail panel.
 *
 * napi-rs maps the snake_case Rust fields to camelCase in TypeScript
 * (`author_name` → `authorName`, etc.).
 */
export interface CommitDetail {
  oid: string
  parents: Array<string>
  authorName: string
  authorEmail: string
  authorTime: number
  committerName: string
  committerEmail: string
  commitTime: number
  message: string
  /**
   * Files changed by this commit relative to its first parent (tree-diff,
   * rename detection OFF). Sorted by path for determinism.
   */
  files: Array<FileChange>
}

/**
 * Fetch full commit detail for a single commit by OID hex string.
 *
 * * `repo_path` — absolute path to the git worktree or `.git` directory.
 * * `oid_hex`   — full 40-character hex OID.
 *
 * Returns author/committer name, email, timestamps, full message, and the
 * list of files changed vs the first parent (tree-diff; rename detection off).
 */
export declare function getCommitDetail(repoPath: string, oidHex: string): CommitDetail

/**
 * Read the raw bytes of a git blob by OID hex string.
 *
 * * `repo_path` — absolute path to the git worktree or `.git` directory.
 * * `oid_hex`   — full 40-character hex OID, or `""` for the missing side of
 *                 an add/delete (returns an empty `Buffer` in that case).
 *
 * Returns the blob's raw bytes as a `Buffer`.
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 */
export declare function getBlob(repoPath: string, oidHex: string): Buffer

/**
 * A single search hit from `findCommits`.
 *
 * napi-rs maps snake_case → camelCase in TypeScript (`row_index` → `rowIndex`,
 * `commit_time` → `commitTime`).
 */
export interface FindMatch {
  /** Full 40-char lowercase hex OID of the matching commit. */
  oid: string
  /** Zero-based row index in the date-order walk — aligns with the paged graph. */
  rowIndex: number
  /** First line of the commit message (subject). */
  subject: string
  /** Author display name. */
  author: string
  /** Committer time as Unix epoch seconds. */
  commitTime: number
}

/**
 * Search the full commit history for commits whose subject, author name, or OID
 * hex prefix matches `query` (case-insensitive substring / prefix).
 *
 * `maxResults` caps the number of hits returned (pass 0 for a built-in cap of
 * 1 000). Returns matches in ascending row-index order.
 *
 * **Row-index contract:** the returned `rowIndex` values align with the rows
 * produced by `getGraphBatch` **only** when both use the same walk order
 * (`SortOrder::Date`, no limit). Changing the paging walk options breaks alignment.
 *
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 */
export declare function findCommits(repoPath: string, query: string, maxResults: number): Array<FindMatch>

/**
 * A single ref (branch or tag) for the release-notes range picker.
 *
 * `kind` is the `RefKind` discriminant: `0` = LocalBranch, `2` = Tag.
 * napi-rs maps snake_case → camelCase (no field renaming needed here).
 */
export interface RefInfo {
  /** Display name (e.g. `"main"`, `"v1.0.0"`). */
  name: string
  /** `RefKind` discriminant: 0=LocalBranch, 2=Tag. */
  kind: number
  /** Full 40-char lowercase hex OID of the commit this ref points at. */
  oid: string
}

/**
 * List all local branches and tags in `repo_path`, sorted branches-first then
 * alphabetically within each group.
 *
 * Stash, remote branches, and HEAD are excluded — only refs a user would
 * name as `from`/`to` range boundaries are returned.
 *
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 */
export declare function listRefs(repoPath: string): Array<RefInfo>

/**
 * One commit in a `from..to` range walk, for release-notes generation.
 *
 * When `includeDiffStat` was `false` on the originating `walkRange` call,
 * `filesChanged`, `insertions`, and `deletions` are all `0`.
 *
 * napi-rs maps snake_case → camelCase: `author_name` → `authorName`,
 * `commit_time` → `commitTime`, `files_changed` → `filesChanged`.
 */
export interface RangeCommit {
  /** Full 40-char lowercase hex OID. */
  oid: string
  /** First line of the commit message. */
  subject: string
  /** Author display name. */
  authorName: string
  /** Committer time as Unix epoch seconds. */
  commitTime: number
  /** Files changed vs first parent. 0 when diffstat is disabled. */
  filesChanged: number
  /** Lines added vs first parent (approximation). 0 when diffstat is disabled. */
  insertions: number
  /** Lines removed vs first parent (approximation). 0 when diffstat is disabled. */
  deletions: number
}

/**
 * Walk commits in `from_rev..to_rev` (newest first).
 *
 * `from_rev` — ref name, OID hex, or rev-spec; pass `null` / `undefined` for
 * the full ancestry of `to_rev`. `to_rev` — same format, e.g. `"HEAD"`.
 * `include_diff_stat` — when `true` each commit's `filesChanged`,
 * `insertions`, and `deletions` are populated (approximate newline counts).
 *
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 */
export declare function walkRange(repoPath: string, fromRev: string | undefined | null, toRev: string, includeDiffStat: boolean): Array<RangeCommit>
