/* auto-generated by napi-derive — do not edit by hand.
 * Regenerate after changing Rust #[napi] exports:
 *   TYPE_DEF_TMP_PATH=/tmp/napi-types.tmp cargo build -p git-braid-napi && \
 *   node scripts/gen-dts.mjs /tmp/napi-types.tmp index.d.ts
 */

/**
 * Request a batch of commit graph rows from the Rust core.
 *
 * # Arguments
 *
 * * `repo_path` — absolute path to the git worktree or `.git` directory.
 * * `offset`    — number of commits already loaded (for incremental paging).
 * * `limit`     — maximum number of commits to return in this batch.
 *
 * # Returns
 *
 * A `Buffer` containing the binary-encoded batch (see `crates/core/src/serialize.rs`).
 * The webview reads this with `DataView` / typed-array views without JSON parsing.
 *
 * # Paging (M1 implementation)
 *
 * M1 re-walks `offset + limit` commits on every call and slices the layout result.
 * This is correct but not optimal for large repos.
 *
 * TODO(M2): accept a serialised `BoundaryState` token so the host can resume layout
 * from the previous batch boundary instead of recomputing from the repository root.
 */
export declare function getGraphBatch(repoPath: string, offset: number, limit: number): Buffer

/** Full detail of a single commit, for the commit detail panel. */
export interface CommitDetail {
  oid: string
  parents: string[]
  authorName: string
  authorEmail: string
  authorTime: number
  committerName: string
  committerEmail: string
  commitTime: number
  message: string
}

/**
 * Fetch full detail for a single commit by OID hex string.
 *
 * @param repoPath — absolute path to the git worktree or `.git` directory.
 * @param oidHex   — full 40-character hex OID.
 */
export declare function getCommitDetail(repoPath: string, oidHex: string): CommitDetail
