/* auto-generated by napi-derive — do not edit by hand.
 * Regenerate after changing Rust #[napi] exports:
 *   TYPE_DEF_TMP_PATH=/tmp/napi-types.tmp cargo build -p git-braid-napi && \
 *   node scripts/gen-dts.mjs /tmp/napi-types.tmp index.d.ts
 */

/**
 * Request a batch of commit graph rows from the Rust core.
 *
 * # Arguments
 *
 * * `repo_path` — absolute path to the git worktree or `.git` directory.
 * * `offset`    — number of commits already loaded (for incremental paging).
 * * `limit`     — maximum number of commits to return in this batch.
 *
 * # Returns
 *
 * A `Buffer` containing the binary-encoded batch (see `crates/core/src/serialize.rs`).
 * The webview reads this with `DataView` / typed-array views without JSON parsing.
 *
 * # Paging (M1 implementation)
 *
 * M1 re-walks `offset + limit` commits on every call and slices the layout result.
 * This is correct but not optimal for large repos.
 *
 * TODO(M2): accept a serialised `BoundaryState` token so the host can resume layout
 * from the previous batch boundary instead of recomputing from the repository root.
 */
export declare function getGraphBatch(repoPath: string, offset: number, limit: number): Buffer

/**
 * A single file-level change introduced by a commit (vs its first parent).
 *
 * `status` is `"A"` (added), `"M"` (modified), or `"D"` (deleted).
 * `old_oid` / `new_oid` are full 40-char hex blob OIDs; the missing side of an
 * add/delete is an empty string `""`.  Rename detection is disabled; renames
 * appear as a deletion + an addition.
 *
 * napi-rs maps snake_case → camelCase in TypeScript.
 */
export interface FileChange {
  path: string
  status: string
  oldOid: string
  newOid: string
}

/**
 * Full detail of a single commit, for the commit detail panel.
 *
 * napi-rs maps the snake_case Rust fields to camelCase in TypeScript
 * (`author_name` → `authorName`, etc.).
 */
export interface CommitDetail {
  oid: string
  parents: Array<string>
  authorName: string
  authorEmail: string
  authorTime: number
  committerName: string
  committerEmail: string
  commitTime: number
  message: string
  /** Files changed by this commit relative to its first parent (tree-diff, rename detection OFF). Sorted by path for determinism. */
  files: Array<FileChange>
}

/**
 * Fetch full commit detail for a single commit by OID hex string.
 *
 * `oid_hex` is the full 40-character hex SHA-1.
 * Returns author/committer name, email, timestamps, full message, and the
 * list of files changed vs the first parent (tree-diff; rename detection off).
 *
 * @param repoPath — absolute path to the git worktree or `.git` directory.
 * @param oidHex   — full 40-character hex OID.
 */
export declare function getCommitDetail(repoPath: string, oidHex: string): CommitDetail

/**
 * Read the raw bytes of a git blob by OID hex string.
 *
 * Returns the blob's raw bytes as a `Buffer`.
 * If `oid_hex` is an empty string, returns an empty `Buffer` — this is the
 * convention for the "missing side" of an addition or deletion in the diff
 * view (so the `gitbraid:` content provider can serve an empty document).
 *
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 *
 * @param repoPath — absolute path to the git worktree or `.git` directory.
 * @param oidHex   — full 40-character hex OID, or `""` for the missing side of
 *                   an add/delete (returns an empty Buffer in that case).
 */
export declare function getBlob(repoPath: string, oidHex: string): Buffer

/**
 * A single search hit from `findCommits`.
 *
 * napi-rs maps snake_case → camelCase in TypeScript (`row_index` → `rowIndex`,
 * `commit_time` → `commitTime`).
 */
export interface FindMatch {
  /** Full 40-char lowercase hex OID of the matching commit. */
  oid: string
  /** Zero-based row index in the date-order walk — aligns with the paged graph. */
  rowIndex: number
  /** First line of the commit message (subject). */
  subject: string
  /** Author display name. */
  author: string
  /** Committer time as Unix epoch seconds. */
  commitTime: number
}

/**
 * Search the full commit history for commits whose subject, author name, or OID
 * hex prefix matches `query` (case-insensitive substring / prefix).
 *
 * `maxResults` caps the number of hits returned (pass 0 for a built-in cap of
 * 1 000). Returns matches in ascending row-index order.
 *
 * **Row-index contract:** the returned `rowIndex` values align with the rows
 * produced by `getGraphBatch` **only** when both use the same walk order
 * (`SortOrder::Date`, no limit). Changing the paging walk options breaks alignment.
 *
 * The read path is gitoxide-only — no `git` subprocess is spawned.
 */
export declare function findCommits(repoPath: string, query: string, maxResults: number): Array<FindMatch>
