#!/usr/bin/env node
/**
 * scripts/gen-dts.mjs — Regenerate bindings/napi/index.d.ts from Rust ///
 * doc comments via the napi-derive TYPE_DEF_TMP_PATH mechanism.
 *
 * Run from the repo root:
 *   pnpm run gen-dts:napi
 *
 * How it works:
 *   1. Touch bindings/napi/src/lib.rs (force cargo to recompile).
 *   2. Run `cargo build -p git-braid-napi` with TYPE_DEF_TMP_PATH set.
 *      napi-derive emits one JSONL line per #[napi] export to that file.
 *   3. Parse the JSONL and render a clean index.d.ts.
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, utimesSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

// Repo root = two dirs up from scripts/
const root = join(fileURLToPath(import.meta.url), '..', '..');
const libRs = join(root, 'bindings/napi/src/lib.rs');
const tmpPath = join(tmpdir(), 'git-braid-napi-types.tmp');
const outPath = join(root, 'bindings/napi/index.d.ts');

// 1. Touch lib.rs to guarantee cargo recompiles (updating mtime is enough).
const now = new Date();
utimesSync(libRs, now, now);
console.log('gen-dts: building napi crate to collect type definitions...');

// 2. Cargo build with TYPE_DEF_TMP_PATH.
execSync('cargo build -p git-braid-napi', {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, TYPE_DEF_TMP_PATH: tmpPath },
});

// 3. Parse JSONL and render d.ts.
const raw = readFileSync(tmpPath, 'utf8').trim();
if (!raw) {
  console.error('gen-dts: ERROR — type def file is empty. No #[napi] exports found.');
  process.exit(1);
}

const HEADER = `/* auto-generated by napi-derive — do not edit by hand.
 * Regenerate after changing Rust #[napi] exports or their /// doc comments:
 *   pnpm run gen-dts:napi
 */\n\n`;

const lines = raw.split('\n').filter(Boolean);
const parts = [];

for (const line of lines) {
  const entry = JSON.parse(line);
  const jsDoc = (entry.js_doc ?? '').trimEnd();

  if (entry.kind === 'fn') {
    const block = jsDoc ? `${jsDoc}\n${entry.def}` : entry.def;
    parts.push(block);
  } else if (entry.kind === 'interface') {
    // Indent each field line (field docs + field decls) by 2 spaces.
    const fields = entry.def
      .split('\n')
      .map(l => (l.trim() ? `  ${l}` : ''))
      .join('\n');
    const block = jsDoc
      ? `${jsDoc}\nexport interface ${entry.name} {\n${fields}\n}`
      : `export interface ${entry.name} {\n${fields}\n}`;
    parts.push(block);
  }
  // 'enum', 'class', etc. — not yet used in this project; skip gracefully.
}

const output = HEADER + parts.join('\n\n') + '\n';
writeFileSync(outPath, output, 'utf8');
console.log(`gen-dts: ✓ wrote ${outPath} (${parts.length} declarations)`);
